### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by SeanTAllen** [seantallen-org/lori#40]
With CirrusCI, It would be good to have Windows CI run so verify that everything works with IOCP on Windows. Most Pony libraries don't need to do this but given the runtime and ASIO heavy nature of Lori, it makes sense to add.

I'm not sure that the current version of Lori works with Windows as I haven't tested with it at all.

**Comment by SeanTAllen** [comment]
See https://cirrus-ci.org/guide/windows/ for Windows documentation for CirrusCI and https://chocolatey.org/packages/visualcpp-build-tools for info on the c++ build tools that would need to be installed via chocolately to download Pony from bintray to install.

**Comment by fkorotkov** [comment]
FYI there is Windows Container 2019 `cirrusci/windowsservercore:cmake` which [has some C-related tools](https://github.com/cirruslabs/docker-images-windows/blob/master/contrib/cmake/Dockerfile).

**Comment by SeanTAllen** [comment]
@fkorotkov thanks for the heads up!
